services:
  - type: web
    name: flask-stock-analyzer
    env: python
    region: oregon  # or choose a different region
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
